### ISSUE TITLE
Sensitivity mapping for 4x is wrong

### ISSUE THREAD

**Issue by beeka** [pimoroni/cap1xxx#18]
The delta_sense bit mapping dictionary looks like this:
`SENSITIVITY = {128: 0b000, 64:0b001, 32:0b010, 16:0b011, 8:0b100, 4:0b100, 2:0b110, 1:0b111}`

Note that the values for 8 and 4 are the same. The CAP1188 datasheet says that 4 should be 0b101.

**Comment by Gadgetoid** [comment]
Ooof! I'll get this corrected when I can.

**Comment by beeka** [comment]
I found this while adding get/set sensitivity functions. I've added my patches, in case they are useful.  [add_sensitivity_fns.txt](https://github.com/pimoroni/cap1xxx/files/4586197/add_sensitivity_fns.txt)
[fix_mapping.txt](https://github.com/pimoroni/cap1xxx/files/4586198/fix_mapping.txt)

**Comment by Gadgetoid** [comment]
Added these as part of https://github.com/pimoroni/cap1xxx-python/pull/23 - thank you!

Hey I'm only- but not quite- four years late!
